# Copyright (c) Intel Corporation
# Copyright (c) 2017
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

cache:
  directories:
  - $HOME/.m2
  - $HOME/build/opensecuritycontroller/osc-core/osc-server-bom/Sources/
sudo: false
language:
    - java
jdk:
    - oraclejdk8
git:
  depth: 99999
addons:
  apt:
    packages:
      - oracle-java8-installer
#Issue with BND tools, see https://github.com/bndtools/bndtools/issues/1294
before_install:
    - mkdir -p $HOME/.bnd/default-ws/cnf/cache/3.3.0/bnd-cache/biz.aQute.launcher
    - wget -O $HOME/.bnd/default-ws/cnf/cache/3.3.0/bnd-cache/biz.aQute.launcher/biz.aQute.launcher-3.3.0.jar http://central.maven.org/maven2/biz/aQute/bnd/biz.aQute.launcher/3.3.0/biz.aQute.launcher-3.3.0.jar
install: 
    true
addons:
  sonarcloud:
    organization: "opensecuritycontroller-org"
    token:
      secure: "yGoFG/dU0vmmn1A63+CiakDGaeUXup/piohBP96SpqM3jfPMNobnMC5vDze9JAx4LMAKsY0Ao+rea5DXJb4U9/hcY3aCDbKT6EodoT5+1tD5sD8riiY8nyVTBchDmyC35AcgM+nXaW8N7ZAj4K0l9EPyHw4fWyK4IwaiJ8gKTD6kvE5ryeahM+SUYPk3vS+d7HwpZeDJFV1XDpZ5kRTew+s68s0pMxDsGW1H6lQ/nWDXc2mHBuvPamtMklhNN5PVdH9JPcttnE4bmOxqLIIjeJTGBMBe2iuP6Pqm33f+Kr8OQ0NOFTN1MLnjcilw8e35Z0aUYRsN6WAwRK4QxIZI6fCXrWzHhrt1YVsTQpMhDGFDFK2vuX0y/2ArTNLxMtIsHBpXlh2dxQ2tCDktxhvtPNzrKYBpFnTr/6VgXFgITHpkw5IYuIM0DeyOzTniVBxDLCnWE6CyKzKrGye9E+t0rpB23shwx4jFadaeLJwl5jr1L+QfRZ1Ufr0TlBLyNGaFpfNWR+pxesdCJJ8poN3fUDV/ThIX8NLVVbZc0RUrgGxZQydPICySAt10aw7qUksXZdK7NZgSUKC2CKOoDY++kPzMjIRPezS5rXVL0LF8Am+xV4Yzv63hFT0NABvXIQ/eX1RH5LfaV2L7Tqm4tT6/t2GNhBbFFcgzIZnF8ZL5U34="
script:
# the following command line builds the project, executes the SonarCloud analysis
    - if [[ -n "${TRAVIS_PULL_REQUEST_SLUG}" || "$(cut -d'/' -f1 <<<${TRAVIS_REPO_SLUG})" != opensecuritycontroller ]]; then
        echo "Skipping sonar analysis as this is a pull request or a build of a fork";
        mvn org.jacoco:jacoco-maven-plugin:prepare-agent install;
      else
        mvn org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar;
      fi
after_success:
    - bash <(curl -s https://codecov.io/bash)